// Configuration file for Trip Cost app
const CONFIG = {
 ORS_API_KEY: 'eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjZlMGI2ZDhjZTE4ZTRlMjI5ZTA1ZDM4MDQyMGRlZjAwIiwiaCI6Im11cm11cjY0In0=',
 EIA_API_KEY: '2mrkKBYZJb6n4QRMSdak0GAnJVxkaVWW1GX3jS2L'
};